############################################################
# +------------------------------------------------------+ #
# |                Simple Configuration                  | #
# +------------------------------------------------------+ #
############################################################

# The number of flags a player has to set off before sending an alert to everyone with the 'xcatch.alert' permission
# 0 for off
alert-flags: 1

# The minimum amount of a type of ore a player has to mine before being able to be flagged
# Format: MATERIAL: AMOUNT
# List of allowed materials: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
rare-ores:
  - ANCIENT_DEBRIS: 16
  - EMERALD_ORE: 12
  - DEEPSLATE_EMERALD_ORE: 12
  - DIAMOND_ORE: 16
  - DEEPSLATE_DIAMOND_ORE: 16
  - GOLD_ORE: 24
  - DEEPSLATE_GOLD_ORE: 24
  - IRON_ORE: 64
  - DEEPSLATE_IRON_ORE: 64
  - REDSTONE_ORE: 64
  - DEEPSLATE_REDSTONE_ORE: 64
  - LAPIS_ORE: 32
  - DEEPSLATE_LAPIS_ORE: 32
  - COPPER_ORE: 48
  - DEEPSLATE_COPPER_ORE: 48
  - NETHER_GOLD_ORE: 48

# Everything above this height will not be counted
# Can reduce false flags of people mining ores in their base
max-height: 256

# The date format used, for more info see https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
date-format: "dd-MM-yyyy 'at' HH:mm z"

############################################################
# +------------------------------------------------------+ #
# |                     Commands                         | #
# +------------------------------------------------------+ #
############################################################

# The command executed when you click a flag inside the flags gui
# Available variables:
# {player}: the player who got flagged
# {x}: X Coordinate location where the ore was found
# {y}: Y Coordinate location where the ore was found
# {z}: Z Coordinate location where the ore was found
# {world}: The name of the world where the ore was found
view-click-command: 'tp {world} {x} {y} {z}'

############################################################
# +------------------------------------------------------+ #
# |                     Messages                         | #
# +------------------------------------------------------+ #
############################################################
# Configure XCatch messages
# Color codes are done with 'ยง'

# Alert message that is sent to staff
# Available variables:
# {player}: the player who got flagged
# {flags}: amount of flags this player has
# {ore}: ore the player was mining
# {amount}: amount of that ore the player has mined
# {x}: X Coordinate location where the ore was found
# {y}: Y Coordinate location where the ore was found
# {z}: Z Coordinate location where the ore was found
# {world}: The name of the world where the ore was found
alert-message: "<click:run_command:'/s {player}'><hover:show_text:'<dark_purple>Click to spectate'><dark_purple>โข</dark_purple> <gray>Flagged (<dark_purple>#{flags}</dark_purple>) <dark_purple>{player}</dark_purple> for potential xray. Mined <dark_purple>{amount} {ore}</dark_purple></gray>"

############################################################
# +------------------------------------------------------+ #
# |                     Advanced                         | #
# +------------------------------------------------------+ #
############################################################
# Only touch this if you know what you're doing!
# This could make it so XCatch doesn't pick up x-ray or gives a lot of false flags

# How many direction changes are required for a flag
changes-for-flag: 5

# The minimum difference of the angle between the previous direction to trigger a direction change
change-angle: 60

# How long you have to keep your angle difference below the 'change-angle' field to reset the tracking data on a player in seconds
# After turning goes back to the value given here
direction-change-retention: 60

# The maximum amount of pending direction changes
# A pending direction change is when you mine a block in a different direction but don't actually go in the direction
# Having a value that is too high might cause false flags when insta-mining
max-pending: 3

# Period after mining a rare ore that no direction changes are recorded in seconds
# This is to avoid false flags after mining an ore
grace-period: 1

# How much time a flag is kept for banning the player or alerting players with the 'xcatch.alert' permission in minutes
# This does not affect the flags in the /xcatch view
flag-retention: 90

# How long until the block reappears
block-retention: 10080