name: XCatch
version: '${project.version}'
main: co.purevanilla.mcplugins.xcatch.Main
api-version: 1.20
authors: [ quiquelhappy, DeDiamondPro ]
description: A simple, efficient plugin to catch x-rayers.
depend:
  - ProtocolLib
commands:
  xreset:
    description: XCatch reset flags
    permission: xcatch.reset
